# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prototype6.ui',
# licensing of 'prototype6.ui' applies.
#
# Created: Sun Oct 31 15:36:27 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 795)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.preview_txt = QtWidgets.QLabel(self.centralwidget)
        self.preview_txt.setGeometry(QtCore.QRect(190, 130, 201, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.preview_txt.setFont(font)
        self.preview_txt.setObjectName("preview_txt")
        self.modif_txt = QtWidgets.QLabel(self.centralwidget)
        self.modif_txt.setGeometry(QtCore.QRect(710, 130, 241, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.modif_txt.setFont(font)
        self.modif_txt.setObjectName("modif_txt")
        self.Cont_1 = QtWidgets.QScrollArea(self.centralwidget)
        self.Cont_1.setGeometry(QtCore.QRect(40, 170, 500, 500))
        self.Cont_1.setWidgetResizable(True)
        self.Cont_1.setObjectName("Cont_1")
        self.con1_widget = QtWidgets.QWidget()
        self.con1_widget.setGeometry(QtCore.QRect(0, 0, 498, 498))
        self.con1_widget.setObjectName("con1_widget")
        self.rgb_img = QtWidgets.QLabel(self.con1_widget)
        self.rgb_img.setGeometry(QtCore.QRect(0, 0, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rgb_img.sizePolicy().hasHeightForWidth())
        self.rgb_img.setSizePolicy(sizePolicy)
        self.rgb_img.setFrameShape(QtWidgets.QFrame.Panel)
        self.rgb_img.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rgb_img.setText("")
        self.rgb_img.setScaledContents(True)
        self.rgb_img.setObjectName("rgb_img")
        self.Cont_1.setWidget(self.con1_widget)
        self.Cont_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.Cont_2.setGeometry(QtCore.QRect(560, 170, 500, 500))
        self.Cont_2.setWidgetResizable(True)
        self.Cont_2.setObjectName("Cont_2")
        self.con2_widget = QtWidgets.QWidget()
        self.con2_widget.setGeometry(QtCore.QRect(0, 0, 498, 498))
        self.con2_widget.setObjectName("con2_widget")
        self.modified_img = QtWidgets.QLabel(self.con2_widget)
        self.modified_img.setEnabled(True)
        self.modified_img.setGeometry(QtCore.QRect(0, 0, 500, 500))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modified_img.sizePolicy().hasHeightForWidth())
        self.modified_img.setSizePolicy(sizePolicy)
        self.modified_img.setText("")
        self.modified_img.setScaledContents(True)
        self.modified_img.setObjectName("modified_img")
        self.Cont_2.setWidget(self.con2_widget)
        self.label_table = QtWidgets.QTableWidget(self.centralwidget)
        self.label_table.setGeometry(QtCore.QRect(1080, 170, 250, 500))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.label_table.setFont(font)
        self.label_table.setObjectName("label_table")
        self.label_table.setColumnCount(1)
        self.label_table.setRowCount(12)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.label_table.setHorizontalHeaderItem(0, item)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(0, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(1, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(2, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(191, 91, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(3, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(237, 28, 36))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(4, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(63, 72, 204))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(5, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(6, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(34, 177, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(7, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(8, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(128, 128, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(9, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(255, 242, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(10, 0, item)
        brush = QtGui.QBrush(QtGui.QColor(128, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(brush)
        self.label_table.setItem(11, 0, item)
        # self.preformance = QtWidgets.QGroupBox(self.centralwidget)
        # self.preformance.setGeometry(QtCore.QRect(1080, 590, 301, 171))
        # self.preformance.setTitle("")
        # self.preformance.setObjectName("preformance")
        # self.accur_txt = QtWidgets.QLabel(self.preformance)
        # self.accur_txt.setGeometry(QtCore.QRect(10, 10, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        # #self.accur_txt.setFont(font)
        # self.accur_txt.setObjectName("accur_txt")
        # self.sens_txt = QtWidgets.QLabel(self.preformance)
        # self.sens_txt.setGeometry(QtCore.QRect(10, 50, 100, 40))
        # font = QtGui.QFont()
        # font.setFamily("Calibri")
        # font.setPointSize(10)
        # font.setWeight(75)
        # font.setBold(True)
        # self.sens_txt.setFont(font)
        # self.sens_txt.setObjectName("sens_txt")
        # self.accr_value = QtWidgets.QLabel(self.preformance)
        # self.accr_value.setGeometry(QtCore.QRect(130, 10, 60, 40))
        # font = QtGui.QFont()
        # font.setFamily("Calibri")
        # font.setPointSize(10)
        # self.accr_value.setFont(font)
        # self.accr_value.setObjectName("accr_value")
        # self.sens_value = QtWidgets.QLabel(self.preformance)
        # self.sens_value.setGeometry(QtCore.QRect(130, 50, 60, 40))
        # font = QtGui.QFont()
        # font.setFamily("Calibri")
        # font.setPointSize(10)
        # self.sens_value.setFont(font)
        # self.sens_value.setObjectName("sens_value")
        self.confi2_box = QtWidgets.QGroupBox(self.centralwidget)
        self.confi2_box.setGeometry(QtCore.QRect(560, 680, 501, 81))
        self.confi2_box.setTitle("")
        self.confi2_box.setObjectName("confi2_box")

        self.angle_btn2 = QtWidgets.QPushButton(self.confi2_box)
        self.angle_btn2.setGeometry(QtCore.QRect(20, 20, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_btn2.sizePolicy().hasHeightForWidth())
        self.angle_btn2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.angle_btn2.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.angle_btn2.setIcon(icon)
        self.angle_btn2.setObjectName("angle_btn2")

        self.scaleL_btn2 = QtWidgets.QPushButton(self.confi2_box)
        self.scaleL_btn2.setGeometry(QtCore.QRect(190, 20, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleL_btn2.sizePolicy().hasHeightForWidth())
        self.scaleL_btn2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.scaleL_btn2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/scalingL.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scaleL_btn2.setIcon(icon1)
        self.scaleL_btn2.setObjectName("scaleL_btn2")

        self.scaleS_btn2 = QtWidgets.QPushButton(self.confi2_box)
        self.scaleS_btn2.setGeometry(QtCore.QRect(360, 20, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleS_btn2.sizePolicy().hasHeightForWidth())
        self.scaleS_btn2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.scaleS_btn2.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/scalingS.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scaleS_btn2.setIcon(icon2)
        self.scaleS_btn2.setObjectName("scaleS_btn2")

        self.confi1_box = QtWidgets.QGroupBox(self.centralwidget)
        self.confi1_box.setGeometry(QtCore.QRect(40, 680, 501, 81))
        self.confi1_box.setTitle("")
        self.confi1_box.setObjectName("confi1_box")

        self.angle_btn = QtWidgets.QPushButton(self.confi1_box)
        self.angle_btn.setGeometry(QtCore.QRect(20, 0, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.angle_btn.sizePolicy().hasHeightForWidth())
        self.angle_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.angle_btn.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/rotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.angle_btn.setIcon(icon3)
        self.angle_btn.setObjectName("angle_btn")

        self.scaleL_btn = QtWidgets.QPushButton(self.confi1_box)
        self.scaleL_btn.setGeometry(QtCore.QRect(190, 0, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleL_btn.sizePolicy().hasHeightForWidth())
        self.scaleL_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.scaleL_btn.setFont(font)
        self.scaleL_btn.setIcon(icon1)
        self.scaleL_btn.setObjectName("scaleL_btn")

        self.scaleS_btn = QtWidgets.QPushButton(self.confi1_box)
        self.scaleS_btn.setGeometry(QtCore.QRect(360, 0, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaleS_btn.sizePolicy().hasHeightForWidth())
        self.scaleS_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.scaleS_btn.setFont(font)
        self.scaleS_btn.setIcon(icon2)
        self.scaleS_btn.setObjectName("scaleS_btn")

        self.zoomin_btn = QtWidgets.QPushButton(self.confi1_box)
        self.zoomin_btn.setGeometry(QtCore.QRect(20, 40, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomin_btn.sizePolicy().hasHeightForWidth())
        self.zoomin_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.zoomin_btn.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/zoomIn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomin_btn.setIcon(icon4)
        self.zoomin_btn.setObjectName("zoomin_btn")

        self.zoomout_btn = QtWidgets.QPushButton(self.confi1_box)
        self.zoomout_btn.setGeometry(QtCore.QRect(190, 40, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoomout_btn.sizePolicy().hasHeightForWidth())
        self.zoomout_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.zoomout_btn.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/zoomOut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoomout_btn.setIcon(icon5)
        self.zoomout_btn.setObjectName("zoomout_btn")

        self.normalsize_btn = QtWidgets.QPushButton(self.confi1_box)
        self.normalsize_btn.setEnabled(True)
        self.normalsize_btn.setGeometry(QtCore.QRect(360, 40, 120, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.normalsize_btn.sizePolicy().hasHeightForWidth())
        self.normalsize_btn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(8)
        self.normalsize_btn.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.normalsize_btn.setIcon(icon6)
        self.normalsize_btn.setObjectName("normalsize_btn")
        self.Header = QtWidgets.QGroupBox(self.centralwidget)
        self.Header.setGeometry(QtCore.QRect(40, 10, 1291, 91))
        self.Header.setTitle("")
        self.Header.setObjectName("Header")
        self.method = QtWidgets.QGroupBox(self.Header)
        self.method.setGeometry(QtCore.QRect(0, 0, 331, 91))
        self.method.setTitle("")
        self.method.setObjectName("method")
        self.method_txt = QtWidgets.QLabel(self.method)
        self.method_txt.setGeometry(QtCore.QRect(10, 30, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.method_txt.setFont(font)
        self.method_txt.setObjectName("method_txt")
        self.method_list = QtWidgets.QComboBox(self.method)

        self.method_list.setGeometry(QtCore.QRect(90, 30, 120, 40))
      
        self.method_list.setMinimumSize(QtCore.QSize(100, 30))
  


        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.method_list.setFont(font)
        self.method_list.setObjectName("method_list")

        self.method_list.addItem("")
        self.method_list.addItem("")
        self.method_list.addItem("")
        self.method_list.addItem("")
        self.method_list.addItem("")
        self.method_list.addItem("")
        self.method_list.addItem("")
      






        self.run_btn = QtWidgets.QToolButton(self.method)
        self.run_btn.setGeometry(QtCore.QRect(220, 30, 91, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.run_btn.setFont(font)
        self.run_btn.setObjectName("run_btn")
        self.result = QtWidgets.QGroupBox(self.Header)
        self.result.setGeometry(QtCore.QRect(330, 0, 351, 91))
        self.result.setTitle("")
        self.result.setObjectName("result")
        self.result_txt = QtWidgets.QLabel(self.result)
        self.result_txt.setGeometry(QtCore.QRect(20, 30, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.result_txt.setFont(font)
        self.result_txt.setObjectName("result_txt")
        self.openimg_btn = QtWidgets.QToolButton(self.result)
        self.openimg_btn.setGeometry(QtCore.QRect(90, 30, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.openimg_btn.setFont(font)
        self.openimg_btn.setObjectName("openimg_btn")
        self.openmask_btn = QtWidgets.QToolButton(self.result)
        self.openmask_btn.setGeometry(QtCore.QRect(220, 30, 120, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.openmask_btn.setFont(font)
        self.openmask_btn.setObjectName("openmask_btn")
        self.blend = QtWidgets.QGroupBox(self.Header)
        self.blend.setGeometry(QtCore.QRect(680, 0, 611, 91))
        self.blend.setTitle("")
        self.blend.setObjectName("blend")
        self.blend_txt = QtWidgets.QLabel(self.blend)
        self.blend_txt.setGeometry(QtCore.QRect(40, 30, 61, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.blend_txt.setFont(font)
        self.blend_txt.setObjectName("blend_txt")
        self.comboBox = QtWidgets.QComboBox(self.blend)
        self.comboBox.setGeometry(QtCore.QRect(110, 30, 140, 40))
        self.comboBox.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.rate_txt = QtWidgets.QLabel(self.blend)
        self.rate_txt.setGeometry(QtCore.QRect(280, 30, 61, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.rate_txt.setFont(font)
        self.rate_txt.setObjectName("rate_txt")

        self.rate_slider = QtWidgets.QSlider(self.blend)
        self.rate_slider.setGeometry(QtCore.QRect(350, 40, 160, 21))
        self.rate_slider.setOrientation(QtCore.Qt.Horizontal)
        self.rate_slider.setObjectName("rate_slider")

        self.rate_slider.setTickPosition(QSlider.TicksBelow)
        self.rate_slider.setTickInterval(10)
        self.rate_slider.setMinimum(0)
        self.rate_slider.setMaximum(10)



        self.rate_value = QtWidgets.QLabel(self.blend)
        self.rate_value.setGeometry(QtCore.QRect(520, 30, 61, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.rate_value.setFont(font)
        self.rate_value.setObjectName("rate_value")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreview = QtWidgets.QAction(MainWindow)
        self.actionPreview.setObjectName("actionPreview")
        self.actionCube = QtWidgets.QAction(MainWindow)
        self.actionCube.setObjectName("actionCube")
        self.actionRGB = QtWidgets.QAction(MainWindow)
        self.actionRGB.setObjectName("actionRGB")
        self.actionSegment = QtWidgets.QAction(MainWindow)
        self.actionSegment.setObjectName("actionSegment")
        self.actionAngle = QtWidgets.QAction(MainWindow)
        self.actionAngle.setIconVisibleInMenu(True)
        self.actionAngle.setObjectName("actionAngle")
        self.actionScale = QtWidgets.QAction(MainWindow)
        self.actionScale.setObjectName("actionScale")
        self.actionBlend = QtWidgets.QAction(MainWindow)
        self.actionBlend.setObjectName("actionBlend")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRecent = QtWidgets.QAction(MainWindow)
        self.actionRecent.setObjectName("actionRecent")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionMask = QtWidgets.QAction(MainWindow)
        self.actionMask.setCheckable(True)
        self.actionMask.setChecked(False)
        self.actionMask.setObjectName("actionMask")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1))
        self.preview_txt.setText(QtWidgets.QApplication.translate("MainWindow", "Rendered RGB image ", None, -1))
        self.modif_txt.setText(QtWidgets.QApplication.translate("MainWindow", "Segmentation image", None, -1))
        self.label_table.verticalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Background", None, -1))
        self.label_table.verticalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Blue dye", None, -1))
        self.label_table.verticalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "ICG", None, -1))
        self.label_table.verticalHeaderItem(3).setText(QtWidgets.QApplication.translate("MainWindow", "Specular reflection", None, -1))
        self.label_table.verticalHeaderItem(4).setText(QtWidgets.QApplication.translate("MainWindow", "Artery", None, -1))
        self.label_table.verticalHeaderItem(5).setText(QtWidgets.QApplication.translate("MainWindow", "Vein", None, -1))
        self.label_table.verticalHeaderItem(6).setText(QtWidgets.QApplication.translate("MainWindow", "Stroma", None, -1))
        self.label_table.verticalHeaderItem(7).setText(QtWidgets.QApplication.translate("MainWindow", "Artery,ICG", None, -1))
        self.label_table.verticalHeaderItem(8).setText(QtWidgets.QApplication.translate("MainWindow", "Stroma,ICG", None, -1))
        self.label_table.verticalHeaderItem(9).setText(QtWidgets.QApplication.translate("MainWindow", "Suture", None, -1))
        self.label_table.verticalHeaderItem(10).setText(QtWidgets.QApplication.translate("MainWindow", "Umbilical cord", None, -1))
        self.label_table.verticalHeaderItem(11).setText(QtWidgets.QApplication.translate("MainWindow", "Red dye", None, -1))
        self.label_table.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "Color", None, -1))
        __sortingEnabled = self.label_table.isSortingEnabled()
        self.label_table.setSortingEnabled(False)
        self.label_table.setSortingEnabled(__sortingEnabled)
        #self.accur_txt.setText(QtWidgets.QApplication.translate("MainWindow", "Accuracy", None, -1))
        #self.sens_txt.setText(QtWidgets.QApplication.translate("MainWindow", "Sensitivity", None, -1))
        #self.accr_value.setText(QtWidgets.QApplication.translate("MainWindow", "97%", None, -1))
        #self.sens_value.setText(QtWidgets.QApplication.translate("MainWindow", "20%", None, -1))
        self.angle_btn2.setText(QtWidgets.QApplication.translate("MainWindow", "Angle", None, -1))
        self.scaleL_btn2.setText(QtWidgets.QApplication.translate("MainWindow", "Upscale", None, -1))
        self.scaleS_btn2.setText(QtWidgets.QApplication.translate("MainWindow", "Downscale", None, -1))
        self.angle_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Angle", None, -1))
        self.scaleL_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Upscale", None, -1))
        self.scaleS_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Downscale", None, -1))
        self.zoomin_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom In", None, -1))
        self.zoomout_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Zoom Out", None, -1))
        self.normalsize_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Reset", None, -1))
        self.method_txt.setText(QtWidgets.QApplication.translate("MainWindow", "Method", None, -1))

        self.method_list.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "U-Net", None, -1))
        self.method_list.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "U-Net-RGB", None, -1))
        self.method_list.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "U-Net-PCA", None, -1))
        self.method_list.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "U-Net-MNF", None, -1))
        self.method_list.setItemText(4, QtWidgets.QApplication.translate("MainWindow", "U-Net-ICA", None, -1))
        self.method_list.setItemText(5, QtWidgets.QApplication.translate("MainWindow", "Swin-Unet", None, -1))
        self.method_list.setItemText(6, QtWidgets.QApplication.translate("MainWindow", "UNet3+", None, -1))
        






        self.run_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Run", None, -1))
        self.result_txt.setText(QtWidgets.QApplication.translate("MainWindow", "Result", None, -1))
        self.openimg_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Open image", None, -1))
        self.openmask_btn.setText(QtWidgets.QApplication.translate("MainWindow", "Open mask", None, -1))
        self.blend_txt.setText(QtWidgets.QApplication.translate("MainWindow", "Blend", None, -1))
        self.comboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Overlay", None, -1))
        self.comboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Multiply", None, -1))
        self.comboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "Lighten", None, -1))
        self.rate_txt.setText(QtWidgets.QApplication.translate("MainWindow", "rate", None, -1))
        self.rate_value.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.actionPreview.setText(QtWidgets.QApplication.translate("MainWindow", "Preview", None, -1))
        self.actionCube.setText(QtWidgets.QApplication.translate("MainWindow", "Cube", None, -1))
        self.actionRGB.setText(QtWidgets.QApplication.translate("MainWindow", "RGB", None, -1))
        self.actionSegment.setText(QtWidgets.QApplication.translate("MainWindow", "Segment", None, -1))
        self.actionAngle.setText(QtWidgets.QApplication.translate("MainWindow", "Angle", None, -1))
        self.actionScale.setText(QtWidgets.QApplication.translate("MainWindow", "Scale", None, -1))
        self.actionBlend.setText(QtWidgets.QApplication.translate("MainWindow", "Blend", None, -1))
        self.actionNew.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.actionOpen.setText(QtWidgets.QApplication.translate("MainWindow", "Open", None, -1))
        self.actionRecent.setText(QtWidgets.QApplication.translate("MainWindow", "Recent ", None, -1))
        self.actionSave.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.actionSave_as.setText(QtWidgets.QApplication.translate("MainWindow", "Save as", None, -1))
        self.actionMask.setText(QtWidgets.QApplication.translate("MainWindow", "Mask", None, -1))
        self.actionMask.setIconText(QtWidgets.QApplication.translate("MainWindow", "Mask", None, -1))
        self.actionMask.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Mask", None, -1))

